190 Remove usages of margin overrides
Newarkandsherwood/housing-repairs-online-frontend pull request #28
Opened 2022-09-01 10:49 UTC by agnieszkazbikowska-madetech

2022-09-01 11:27 UTC, agnieszkazbikowska-madetech commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove usages of margin overrides](https://trello.com/c/l4GY4Iv8/190-remove-usages-of-margin-overrides)

2022-09-05 09:41 UTC, markWarr requested changes

2022-09-05 09:44 UTC, agnieszkazbikowska-madetech commented on compoments/report-repair/confirmation.js
> +        <p>
All done!

2022-09-05 09:45 UTC, markWarr approved these changes

2022-09-05 10:00 UTC, merged